### ISSUE TITLE
Error occured when using upload-cloud-storage

### ISSUE THREAD

**Issue by shwuhk** [google-github-actions/upload-cloud-storage#10]
- name: Upload to Google Cloud Storage
        uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@master
        with:
          credentials: ${{ secrets.GCS_CREDENTIALS }}
          path: build
          destination: ${{ env.UPLOAD_PATH_NAME }}

Error: A resumable upload could not be performed. The directory, /root/.config, is not writable. You may try another upload, this time setting `options.resumable` to `false`.

**Comment by bharathkkb** [comment]
Hi @shwuhk, thanks for the report!

It may make sense to expose this? How big are the files you are trying to upload? Does a path like `/root/.config` exist?

**Comment by shwuhk** [comment]
@bharathkkb 
Several MBs file. `/root/.config` does not exist as this is an empheral machine.

**Comment by sethvargo** [comment]
From https://github.com/googleapis/nodejs-storage/issues/807, it looks like gsutil expects `configPath` to be set to a writable path. I think it should be set to something in /tmp or /home/github.

**Comment by bharathkkb** [comment]
fixed by https://github.com/google-github-actions/upload-cloud-storage/pull/34
