### ISSUE TITLE
release-please job failing

### ISSUE THREAD

**Issue by bharathkkb** [google-github-actions/upload-cloud-storage#12]
### TL;DR
Release-please action is failing. Seems related to  https://github.com/google-github-actions/release-please-action/issues/164. Workaround will be to pin to previous version

**Expected behavior**

**Observed behavior**

### Reproduction

**Action YAML**

```yaml
# Paste your complete GitHub Actions YAML here, removing
# any sensitive values.
```

**Repository**

**Additional information**

**Comment by bcoe** [comment]
@bharathkkb I believe I have fixed this.

**Comment by bharathkkb** [comment]
just saw :) Thanks for the quick fix @bcoe
