### ISSUE TITLE
v0 tag does not exist.

### ISSUE THREAD

**Issue by arenoir** [google-github-actions/upload-cloud-storage#164]
FYI,

I am getting the following error when trying to use this action following the example in the readme.

```
Error: Unable to resolve action `google-github-actions/upload-cloud-storage@v0`, unable to find version `v0`
```

It looks like github actions doesn't use semantic versioning and will not resolve v0 to the latest v0.4.2 tag.   I am guessing a v0 tag needs to be created and updated whenever a new version is released. 

Perhaps a `latest` branch could be used instead?

Thanks.

**Comment by sethvargo** [comment]
Yea, we have automation to do this, but it's not fully rolled out yet. I just tagged `v0` manually.

Refs https://github.com/google-github-actions/upload-cloud-storage/pull/159
