### ISSUE TITLE
"credentials" input has been deprecated - is it true?

### ISSUE THREAD

**Issue by taranovichevich** [google-github-actions/upload-cloud-storage#212]
### Question

How is this action supposed to work without `credentials` if a client that uploads files/folders is still using them?
https://github.com/google-github-actions/upload-cloud-storage/blob/main/src/main.ts#L63

**Comment by sethvargo** [comment]
We've separated "authentication to google cloud" into its own step:

```yaml
uses: google-github-actions/auth@v0

uses: google-github-actions/upload-cloud-storage@v0
```

There are some more complete examples in the readme https://github.com/google-github-actions/upload-cloud-storage#for-uploading-a-file. 

Let me know if you have other questions.

**Comment by sethvargo** [comment]
Or are you asking specifically about:

https://github.com/google-github-actions/upload-cloud-storage/blob/b5dd2b4bed766f174d8238b2269ff3ca8a50a0bb/src/main.ts#L63

When `credentials` is undefined, the library falls back to Application Default Credentials. That means it will resolve the credentials exported by the auth step.

Once we actually remove the `credentials` input from this action, that line will become:

```node
const client = new Client();
```
