### ISSUE TITLE
Failed by timeout on a large number of files

### ISSUE THREAD

**Issue by levonet** [google-github-actions/upload-cloud-storage#24]
We use this action to upload reports after building projects.
Upload fails in one of the big projects. After 8 minutes, an error occurs:
```
Error: Multiple errors occurred during the request. Please see the `errors` array for complete details.

    1. Request Timeout
    2. <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style><!-- skip --></style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>408.</b> <ins>That’s an error.</ins>
  <p>Your client has taken too long to issue its request.  <ins>That’s all we know.</ins>
```

Characteristics of the directory for uploading:
```
# find target/site/clover -type f | wc -l 
    3645
# du -sh target/site/clover
107M	target/site/clover
```
For other smaller projects, this action works perfectly.

If I setup `google-github-actions/setup-gcloud` and run `gsutil -mq cp -r <path> <destination>` then the uploading is successful within 2 minutes.

I can't link to the code because the repository is not public.

**Comment by bharathkkb** [comment]
Hi @levonet 
We recently added a few features on main that may help.  Previously we were not limiting concurrency and for 3k files, this would mean potentially 3k requests in flight. 

Now we set default `concurrency` to `10` and you can also control it if needed. Uploads are also resumable by default which should help.  Let us know if these help or if this issue still happens.

**Comment by levonet** [comment]
Thank you very much for the correction, we will try to check soon.

**Comment by bharathkkb** [comment]
@levonet feel free to reopen if still an issue

**Comment by levonet** [comment]
For history https://github.com/google-github-actions/upload-cloud-storage/pull/33
