### ISSUE TITLE
v0.10.0 - uploading a file uploads it with the containing directory 

### ISSUE THREAD

**Issue by OmerGery** [google-github-actions/upload-cloud-storage#259]
### TL;DR

the upload logic has changed on v0.10.0 - the uploaded file is a folder containing the desired file instead of only the actual file.

### Expected behavior

When uploading 
path: './A/B/myfile.apk'
i expected myfile.apk only to be uploaded, this was the way it worked until v0.9.0. 

### Observed behavior

for some reason the logic has changed on v0.10.0 to uploading 'B/myfile.apk' . this is a bug. if i wanted to upload 'B/myfile.apk' i will select the path to be './A/B'.

### Action YAML

```yaml
i can't unfortunately as it is a private org repo. but the bug can be recreated really easily, a folder will be uploaded instead of just a file as i explained.
```

**Comment by sethvargo** [comment]
Hi @OmerGery 

Thank you for opening an issue. It would be helpful if you had the debug log output we could look at between the two runs. The new behavior you described is exactly how the behavior is documented. I think you would want to have [set [`parent: false`](https://github.com/google-github-actions/upload-cloud-storage#upload-to-bucket-root) to upload to the root.

**Comment by sethvargo** [comment]
Hi @OmerGery 

We didn't intend for this to be a breaking change, so I'd like to better understand the behavior prior to 0.10.

**Comment by alokedesai** [comment]
@sethvargo This is also broken for us (warpdotdev: https://warp.dev). The semantics of this action seem to have changed (we also can confirm that running at versions before 0.10 result in the _correct_ behavior), which seems to imply it was a breaking change. 

Would it be possible to rollback or fix forward with the correct behavior? Happy to send you the debug log output if you send me your ldap (would prefer to not post publicly since our repo in the off chance there's any private information in it).

**Comment by ben-marengo-msmg** [comment]
also surprised by backward incompatibility. heres our log output of the action.
action is very simple, no changing default working directory or anything

![Screenshot 2022-04-28 at 12 21 23](https://user-images.githubusercontent.com/85871954/165742535-7e8d9ff7-2e19-4eed-bab0-f9c5c8a5554c.png)
![Screenshot 2022-04-28 at 12 21 32](https://user-images.githubusercontent.com/85871954/165742541-7b3fd1dc-cfd1-4d9a-b158-b65ae8c5cce6.png)

**Comment by sethvargo** [comment]
Hi @alokedesai - thank you for the info. You can pin to `google-github-actions/upload-cloud-storage@v0.9.0` while we investigate.
