### ISSUE TITLE
Cache based on Checksum

### ISSUE THREAD

**Issue by andreas-fahrecker** [google-github-actions/upload-cloud-storage#299]
### TL;DR

Upload files only when the checksum is different from the repo file to the CloudStorage file.

### Detailed design

If a file already exists in the CloudStorage Bucket with the same name as a file to be uploaded by the Action,
then the file should be downloaded first. Then the checksums of the files with identical names should be compared.
And finally the file defined to be uploaded to the CloudStorage Bucket should only be uploaded when the checksum has changed.

**Comment by sethvargo** [comment]
Hi @andreas-fahrecker 

What is the use case for this? It sounds like you might want to use `gsutil rsync` instead: https://cloud.google.com/storage/docs/gsutil/commands/rsync

**Comment by andreas-fahrecker** [comment]
Thanks for the fast response @sethvargo 

Seems like that would do the job, is there a Github Action for that?

**Comment by sethvargo** [comment]
You can use `setup-gcloud` to install `gsutil` and then just run the gsutil command.
