### ISSUE TITLE
How to Copy Files/Folder from Github Action to Google Cloud Storage (Bucket) 

### ISSUE THREAD

**Issue by MohdRashid01** [google-github-actions/upload-cloud-storage#302]
Hi All,

Please have a look at below ticket 

https://github.com/orgs/community/discussions/40102

**Comment by sethvargo** [comment]
Hi @MohdRashid01 

Please submit an issue using our bug report issue template: https://github.com/google-github-actions/upload-cloud-storage/issues/new?assignees=&labels=bug&template=bug.yaml. This will collect the information we need to assist.
