### ISSUE TITLE
Rename a file when copying

### ISSUE THREAD

**Issue by elitongadotti** [google-github-actions/upload-cloud-storage#340]
### TL;DR

Similar to when we use `gsutil cp` (below), it would be great to rename the file **when** the `destination` is not a bucket.

`gsutil cp source/file.txt gs://bucket/new_file_name.txt`

### Detailed design

Otherwise, the option would be use `gsutil` anyway to rename it. The improvement is on avoid using a different action (less lines/verbosity)

**Comment by sethvargo** [comment]
Hi there - we are aiming to keep the surface area of this function small. If you are just uploading a single file and want to rename it, it will be better to use `gcloud storage cp`. That should be a drop-in-replace for the `upload-cloud-storage` action.
