### ISSUE TITLE
Add support for delete-unmatched

### ISSUE THREAD

**Issue by craigh1015** [google-github-actions/upload-cloud-storage#372]
### TL;DR

Similar to using `gcloud storage rsync <source-folder> <bucket> --recursive --delete-unmatched-destination-objects`.
Provide a mechanism to ensure that the destination bucket is an exact replica of the source folder.

### Detailed design

Add an input `delete-unmatched` with a default of `false`.

**Comment by sethvargo** [comment]
Hi @craigh1015 - we don't expose every option in this action because otherwise the surface becomes unwieldy. I recommend using `setup-gcloud` and running that `gcloud` command directly instead.

**Comment by craigh1015** [comment]
Thanks, I just found `setup-gcloud` and was coming back here to write an update

**Comment by Ronkiro** [comment]
throwing a reference of how to do it for who gets here

https://stackoverflow.com/a/68374007/10473393
