### ISSUE TITLE
Copy only Modified files

### ISSUE THREAD

**Issue by chandanpg** [google-github-actions/upload-cloud-storage#379]
### TL;DR

There should be a input parameter by using that it should copy only those files which are modified in source folder. Ex. If you have 100 files in source but you have modified 2 files and when copying, it should copy only those modified files. This would be very useful for Composer when copy Dags files.

**Comment by sethvargo** [comment]
Hi @chandanpg - thank you for opening an issue. This is conceptually similar to some of the requests we've gotten for rsync in the past (https://github.com/google-github-actions/upload-cloud-storage/issues/372, https://github.com/google-github-actions/upload-cloud-storage/issues/350, https://github.com/google-github-actions/upload-cloud-storage/issues/63).

The purpose of this GitHub Action is to upload all files in a directory on disk into a GCS bucket. More advanced use cases should install and use the `gcloud` CLI (`gcloud storage ...`) or write a custom shell script to handle their specific use case.
