### ISSUE TITLE
What happens if a directory already exists when copying a directory?

### ISSUE THREAD

**Issue by kruncher** [google-github-actions/upload-cloud-storage#40]
### Question

If a GitHub action copies a build directory into a bucket using this action; what happens if a directory with the same name already exists in the target bucket?

Does it get replaced, merged, or does it simply fail?

**Comment by bharathkkb** [comment]
@kruncher The action deals with files in directory individually. If the target bucket has `foo/bar.txt` and you try to upload to `foo/bar.txt`, it will be replaced. If you try to upload `foo/baz.txt`, the bucket will now contain `foo/bar.txt` and `foo/baz.txt`. Hope that answers the question.
